# Generated by Django 4.2.7 on 2023-11-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeApp', '0003_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
